### PR TITLE
fix: metadata value type is changed from string to byte array

### LINKED ISSUE #401: Metadata - problem with editing metadata value
Same issue with https://github.com/symbol/symbol-sdk-typescript-javascript/issues/834

### PR DESCRIPTION
**Pull request by yilmazbahadir**
fixes #401

Failure_Metadata_Value_Size_Delta_Mismatch

### What's the fix?
We noticed that `value` field in the Metadata Transactions(`AccountMetadataTransaction`, `NamespaceMetadataTransaction`, `MosaicMetadataTransaction`) has the type `string`.
This was the root cause of the issue, since the `value` field was meant to be a difference between the previous and the new value in _bytes_, converting the difference to first `string` and then to `byte[]` was resulting in loss of bytes and therefore sending wrong information to the `catapult-rest`.

In order to fix this, we:
* Changed the `value` type from `string` to `byte[]`

### CODE REVIEW

**Review by cryptoBeliever — APPROVED** [review]

File: sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/MetadataTransaction.java [hunk 1]
```diff
@@ -38,7 +38,7 @@
    * value is an hex string as it comes from the rest objects. Value is converted to byte array when
    * serialized to Catbuffer.
    */
-  private final String value;
+  private final byte[] value;
```
Comment (gimre-xymcity) [inline sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/MetadataTransaction.java:41]: 🤔 wasn't this code generated?

File: sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java [hunk 2]
```diff
@@ -487,7 +488,8 @@ void shouldCreateAggregateMosaicMetadataTransaction() {
     Assertions.assertEquals(
         new BigInteger("11529215046069664444"), transaction.getScopedMetadataKey());
     Assertions.assertEquals(
-        "This is the message for this account! 汉字89664", transaction.getValue());
+        "This is the message for this account! 汉字89664",
```
Comment (gimre-xymcity) [inline sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java:491]: it's probably left  side (expected) that should be encoded (instead of `.getString(value)`, but ask @Jaguar0625

File: sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/MetadataTransaction.java (hunk 1 above)
Comment (yilmazbahadir) [reply sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/MetadataTransaction.java:41]: I think it's not, cannot see any indication in the code.

File: sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java (hunk 2 above)
Comment (yilmazbahadir) [reply sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java]: Got it.
I just updated most of the assertions to have _encoding in the `expected value` side_ so that `actual value` stays raw.

Comment (0x6861746366574) [reply sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java]: @gimre-xymcity @Jaguar0625 I'd leave encoding as is, no?

**Review by gimre-xymcity — APPROVED** [review]
